apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: genai-frontend-ingress
  namespace: genai-frontend
  labels:
    app: genai-user-mgmt
    tier: frontend
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: frontend.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: genai-frontend-service
                port:
                  number: 80

