apiVersion: v1
kind: Service
metadata:
  name: genai-frontend-service
  namespace: genai-frontend
  labels:
    app: genai-user-mgmt
    tier: frontend
spec:
  type: ClusterIP
  selector:
    app: genai-user-mgmt
    tier: frontend
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP

